name: vercel_deploy

on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create env file
      shell: bash
     
      run: |
        ls
        touch .env
        echo "MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }}" >> .env
        npm install
        npm run build
        
    - uses: amondnet/vercel-action@v20.0.1
      with:
        # GitHub Actions の Secrets で作成した値を参照する形で
        # Vercel デプロイ時に必要となる各種パラメタを設定する
        vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
        vercel-args: '--prod' # Optional
        vercel-org-id: ${{ secrets.ORG_ID}}  #Required
        vercel-project-id: ${{ secrets.PROJECT_ID}} #Required
        working-directory: ./

